### PR TITLE
CDAP-14932 Salesforce Batch Source to fetch objects via SOQL. Initial structure.

### PR DESCRIPTION
**Pull request by aonischuk**
Build related stuff. 

In pom.xml I added some dependencies which will be needed in future/already used in my draft code

### CODE REVIEW

**Comment by albertshau** [comment]
That header was copy-pasted from somewhere else, please keep using Cask Data. If we switch over we'll do them all at the same time.

**Comment by aonischuk** [comment]
@albertshau fixed the headers.

**Comment by aonischuk** [comment]
Also I saw that package name Bhooshan had was com.google.plugins not co.cask.plugins. Should I use cask as well?

**Comment by albertshau** [comment]
yep

**Comment by aonischuk** [comment]
@albertshau fixed that as well. Does the patch look good to go?

**Pull request merged**
